/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-library-conventions")
}

dependencies {
    api(project(":list"))
    // implementation group: 'org.jetbrains.kotlin', name: 'kotlin-test', version: '1.9.22'
    testImplementation(Dependencies.kotlinTest)

}
