/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example.app

import connectToDatabase
import id.UserId
import repositories.UserReadRepositoryImpl
import repositories.getByIdOrNull

fun main() {
    val database = connectToDatabase()

    val userRepo = UserReadRepositoryImpl(database)
    val user = userRepo.getByIdOrNull(UserId.dontUseThisDirectly(1))
    println(user)
}
